#!/usr/bin/env python3
"""Turn the WeChat QR image into a module matrix for the terminal homepage.

The terminal (/cli, /cli.py) cannot show a PNG, so it draws the QR code with half-block
characters. This script decodes assets/img/social/wechat-qr.png, re-encodes the same payload
(error correction M, smallest version), verifies the result decodes back to the same payload,
and writes the module matrix plus the PNG's SHA-256 to _data/terminal_qr.yml. The build has no
QR dependency; validate_content.py fails if the PNG changes without rerunning this script.

    pip install opencv-python-headless segno
    python3 scripts/terminal_qr.py
"""

from __future__ import annotations

import hashlib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "img" / "social" / "wechat-qr.png"
OUTPUT = ROOT / "_data" / "terminal_qr.yml"


def decode(image) -> str:
    import cv2

    detector = cv2.QRCodeDetector()
    for scale in (1, 2, 3):
        candidate = image if scale == 1 else cv2.resize(image, None, fx=scale, fy=scale, interpolation=cv2.INTER_NEAREST)
        payload, _points, _straight = detector.detectAndDecode(candidate)
        if payload:
            return payload
    return ""


def main() -> int:
    try:
        import cv2
        import numpy as np
        import segno
    except ImportError:
        print("needs: pip install opencv-python-headless segno", file=sys.stderr)
        return 2

    payload = decode(cv2.imread(str(SOURCE)))
    if not payload:
        print(f"could not decode {SOURCE.relative_to(ROOT)}", file=sys.stderr)
        return 1

    code = segno.make(payload, error="M", micro=False)
    rows = ["".join("1" if module else "0" for module in row) for row in code.matrix]

    # Round trip: render the matrix (with a quiet zone) and make sure it decodes to the same payload.
    size, scale, border = len(rows), 8, 4
    canvas = np.full(((size + 2 * border) * scale,) * 2, 255, dtype=np.uint8)
    for y, row in enumerate(rows):
        for x, module in enumerate(row):
            if module == "1":
                canvas[(y + border) * scale : (y + border + 1) * scale, (x + border) * scale : (x + border + 1) * scale] = 0
    if decode(cv2.cvtColor(canvas, cv2.COLOR_GRAY2BGR)) != payload:
        print("re-encoded matrix does not decode back to the original payload", file=sys.stderr)
        return 1

    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    lines = [
        "# Generated by scripts/terminal_qr.py — do not edit. Module matrix of the WeChat QR code",
        "# (same payload as assets/img/social/wechat-qr.png) for the terminal homepage.",
        f"source: {SOURCE.relative_to(ROOT).as_posix()}",
        f"source_sha256: {digest}",
        f"version: {code.version}",
        "error: M",
        "rows:",
        *[f'  - "{row}"' for row in rows],
    ]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUTPUT.relative_to(ROOT)}: version {code.version}, {size}x{size} modules, round trip ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
